### ISSUE TITLE
Collaboration with oshi

### ISSUE THREAD

**Issue by dbwiddis** [profesorfalken/jHardware#2]
I'm the lead maintainer for [OSHI](https://github.com/dblock/oshi), a project that looks to have similar goals to yours in providing Java access to operating system/hardware information.   The main difference appears to be that OSHI depends on JNA and native code, while you're primarily focused on command-line scripting.  Additionally OSHI works on OS X.

A brief review of your code shows some bits I'd like to use as inspiration for features in OSHI.  Similarly I'd be interested in helping contribute a mac OS X port to your code.   Let me know how best we can coordinate our efforts.

I'll be adding a link to your project from my README.

**Comment by profesorfalken** [comment]
Hi, 
I did not now OSHI project before. If I did maybe I would never start mine :-)

The first version of jHarware used JNI in order to scrap data from system, but I realized that at the end I could get Linux information using commands and Windows information using WMI queries, so I rewrite all in pure Java.

Of course, you can take everything you want from jHardware and I will add a link to OSHI in my README. I will take a closer look to that project when I find time...

Nice to meet you and thank you for your help

**Comment by dbwiddis** [comment]
Happy to help!  You have some cool information (network, bios) that I have not yet implemented and it appears you have some sudo capability as well, which is nice.   I think our projects can be very complimentary to each other.
