### ISSUE TITLE
Total Physical Memory on Windows is incorrect

### ISSUE THREAD

**Issue by silpamittapalli** [profesorfalken/jHardware#8]
WindowsMemoryInfo is using  "FreePhysicalMemory" for total memory, while it is supposed to use "TotalPhysicalMemory" instead.

Related code snippet from WindowsMemoryInfo -

memoryDataMap.put("MemFree", 
                WMI4Java.get().VBSEngine().getWMIObject(WMIClass.WIN32_OPERATINGSYSTEM).get("FreePhysicalMemory"));
        memoryDataMap.put("MemTotal", WMI4Java.get().VBSEngine().getWMIObject(WMIClass.WIN32_OPERATINGSYSTEM).get("FreePhysicalMemory"));

**Comment by profesorfalken** [comment]
Hello, 
You are right. I will create a fixed version.

Thank you

**Comment by silpamittapalli** [comment]
Thanks! Can we get a timeline on when to expect the fix?

**Comment by profesorfalken** [comment]
Hello, 

Since this is an open source project maintained in my free time, I do not have specific timelines. However, as the source code is public, everyone is free to fix/modify/improve it if needed.

In this case, I have found some time and I have already quickly made the fix. The 0.8.4 version will be available on Maven Central in few hours from now. 

Best regards and thank that you for your help!
